from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import login_view


urlpatterns = [

    path('', views.inicio, name='inicio'),   
    path('home/', views.home, name='home'), 
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registro/', views.registro_paciente, name='registro_paciente'),
    path('administrador/crear-usuario/', views.crear_usuario, name='crear_usuario'),
    path('administrador/usuarios/', views.listar_usuarios, name='listar_usuarios'),
    path('administrador/editar-usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('administrador/eliminar-usuario/<int:user_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('administrador/pacientes/', views.lista_pacientes, name='lista_pacientes'),
    path('admin/slider/', views.slider_agregar, name='slider_agregar'),
    path('desbloquear-usuario/<int:id>/', views.desbloquear_usuario, name='desbloquear_usuario'),
    path('perfil/editar/', views.actualizar_datos, name='actualizar_datos'),
    path('perfil/cambiar-password/', views.cambiar_password, name='cambiar_password'),
    path('pacientes/', views.pacientes_home, name='pacientes_home'),
    path('examen/', views.lista_examenes, name='lista_examenes'),
    path('buscar-pacientes/', views.buscar_pacientes, name='buscar_pacientes'),
    path('historia-medica/<str:tipo>/<int:paciente_id>/', views.historia_medica_modal, name='historia_medica_modal'),
    path('paciente/historia/ver/<str:tipo>/<int:paciente_id>/', views.ver_historia_medica, name='ver_historia_medica'),
    path('enfermera/', views.enfermera_home, name='enfermera_home'),
    path('doctor/', views.doctor_home, name='doctor_home'),
    path('registrar/horario/<int:doctor_id>/', views.registrar_horario, name='registrar_horario'),
    path('perfil/editar/doctor', views.editar_perfil_doctor, name='editar_perfil_doctor'),
    path('horario/editar/<int:horario_id>/', views.editar_horario, name='editar_horario'),
    path('horario/eliminar/<int:horario_id>/', views.eliminar_horario, name='eliminar_horario'),
    path('doctores/', views.lista_doctores, name='lista_doctores'),
    path('buscar-doctores/', views.buscar_doctores, name='buscar_doctores'),
    path('especialidades/', views.especialidades, name='especialidades'),
    path('editar-especialidad/<int:id>/', views.editar_especialidad, name='editar_especialidad'),
    path('eliminar-especialidad/<int:id>/', views.eliminar_especialidad, name='eliminar_especialidad'),
    path('insumos/', views.insumos, name='insumos'),
    path('insumos/lista/', views.lista_insumos, name='lista_insumos'),
    path('insumos/editar/<int:insumo_id>/', views.editar_insumo, name='editar_insumo'),
    path('insumos/eliminar/<int:insumo_id>/', views.eliminar_insumo, name='eliminar_insumo'),
    path('insumos/mostrar/<int:insumo_id>/', views.mostrar_insumo, name='mostrar_insumo'),
    path('solicitar-cita/', views.solicitar_cita, name='solicitar_cita'),
    path('mis-citas/', views.mis_citas, name='mis_citas'),
    path('cancelar-mi-cita/<int:cita_id>/', views.cancelar_mi_cita, name='cancelar_mi_cita'),
    path('lista-citas/', views.lista_citas, name='lista_citas'),
    path('crear-cita-admin/', views.crear_cita_admin, name='crear_cita_admin'),
    path('editar-cita-admin/<int:cita_id>/', views.editar_cita_admin, name='editar_cita_admin'),
    path('confirmar-cita/<int:cita_id>/', views.confirmar_cita, name='confirmar_cita'),
    path('marcar-cita-atendida/<int:cita_id>/', views.marcar_cita_atendida, name='marcar_cita_atendida'),
    path('cancelar-cita-admin/<int:cita_id>/', views.cancelar_cita_admin, name='cancelar_cita_admin'),
    path('eliminar-cita-admin/<int:cita_id>/', views.eliminar_cita_admin, name='eliminar_cita_admin'),
    path('obtener-horas-disponibles/', views.obtener_horas_disponibles, name='obtener_horas_disponibles'),
    path('citas-doctor/', views.citas_doctor, name='citas_doctor'),
    path('atender-cita/<int:cita_id>/', views.atender_cita, name='atender_cita'),
    path('ver_factura/<int:cita_id>/', views.ver_factura, name='ver_factura'),
    path('factura/print/<int:cita_id>/', views.ver_factura_print, name='ver_factura_print'),
    path('agregar-stock/<int:insumo_id>/', views.agregar_stock, name='agregar_stock'),
    path('entrada/<int:insumo_id>/', views.entrada_insumo, name='entrada_insumo'),  
    path('doctores/pdf/', views.seleccion_pdf_doctores, name='seleccion_pdf_doctores'),
    path('doctores/pdf/generar/', views.pdf_doctores_horarios, name='pdf_doctores_horarios'),
    path('administrador/', views.admin_home, name='admin_home'),
    path('examen/editar/<int:examen_id>/', views.editar_examen, name='editar_examen'),
    path('examen/eliminar/<int:examen_id>/', views.eliminar_examen, name='eliminar_examen'),
    path('examenes/', views.examenes, name='examenes'),
    path('inventario/historial/<int:insumo_id>/', views.historial_stock, name='historial_stock'),
    path('examenes/disponibles/', views.examenes_disponibles, name='examenes_disponibles'),
    path('doctores/disponibles/', views.doctores_disponibles, name='doctores_disponibles'),
    path('slider/agregar/', views.slider_agregar, name='slider_agregar'),
    path('slider/listado/', views.slider_listado, name='slider_listado'),
    path('slider/estado/<int:pk>/', views.alternar_estado_slider, name='alternar_estado_slider'),
    path('slider/eliminar/<int:pk>/', views.eliminar_slider, name='eliminar_slider'),
    path('bcv/crear/', views.crear_bcv, name='crear_bcv'),
    path('registrar-examen/', views.registrar_examen, name='registrar_examen'),
    path('listar-examenes/', views.listar_examenes, name='listar_examenes'),
    path('detalle-examen/<int:examen_id>/', views.detalle_examen, name='detalle_examen'),  
    path('examenes/<int:examen_id>/print/', views.detalle_examen_print, name='detalle_examen_print'),
    path('reportes/pacientes/', views.reporte_pacientes, name='reporte_pacientes'),
    path('reportes/pacientes/pdf/', views.generar_pdf_pacientes, name='generar_pdf_pacientes'),
    path('reportes/contabilidad/', views.reportes_contabilidad, name='reportes_contabilidad'),
    path('reportes/citas/', views.reporte_citas, name='reporte_citas'),
    path('reportes/citas/pdf/', views.generar_pdf_citas, name='generar_pdf_citas'),
    path('reportes/insumos/', views.reporte_insumos, name='reporte_insumos'),
    path('reportes/insumos/pdf/', views.generar_pdf_insumos, name='generar_pdf_insumos'),
    path('reportes/examenes/', views.reporte_examenes, name='reporte_examenes'),
    path('reportes/examenes/pdf/', views.generar_pdf_examenes, name='generar_pdf_examenes'),
    path('grafico_consumo_insumos/', views.grafico_consumo_insumos, name='grafico_consumo_insumos'),
    path('estadisticas-mensuales/', views.estadisticas_mensuales, name='estadisticas_mensuales'),
    path('crear-familiar/', views.crear_familiar, name='crear_familiar'),
    path('crear-familiar-admin/', views.crear_familiar_admin, name='crear_familiar_admin'),
    path('crear-familiar-paciente/', views.crear_familiar_paciente, name='crear_familiar_paciente'),
    path('mis-familiares/', views.mis_familiares, name='mis_familiares'),
    path('editar-familiar/<int:familiar_id>/', views.editar_familiar_paciente, name='editar_familiar_paciente'),
    path('eliminar-familiar/<int:familiar_id>/', views.eliminar_familiar_paciente, name='eliminar_familiar_paciente'),
    path('lista-carga-familiar-admin/', views.lista_carga_familiar_admin, name='lista_carga_familiar_admin'),  
    path('mis-examenes/', views.mis_examenes_medicos, name='mis_examenes'),
    path('doctor/examenes/', views.mis_examenes_doctor, name='mis_examenes_doctor'),
    path('doctor/examenes/registrar/<int:cita_id>/', views.registrar_examen_doctor, name='registrar_examen_doctor'),
    path('doctor/examenes/<int:examen_id>/', views.detalle_examen_doctor, name='detalle_examen_doctor'),
    path('doctor/examenes/<int:examen_id>/print/', views.detalle_examen_doctor_print, name='detalle_examen_doctor_print'),

    # Emergencias
    path('emergencias/registrar/', views.registrar_emergencia, name='registrar_emergencia'),
    path('emergencias/lista/', views.lista_emergencias, name='lista_emergencias'),
    path('emergencias/<int:emergencia_id>/', views.detalle_emergencia, name='detalle_emergencia'),
    path('emergencias/<int:emergencia_id>/estado/', views.cambiar_estado_emergencia, name='cambiar_estado_emergencia'),
    path('emergencias/<int:emergencia_id>/triaje/', views.triaje_modal, name='triaje_modal'),
    path('emergencias/<int:emergencia_id>/triaje/ver/', views.ver_triaje, name='ver_triaje'),
    path('emergencias/<int:emergencia_id>/evaluacion/', views.evaluacion_emergencia, name='evaluacion_emergencia'),
    path('emergencias/<int:emergencia_id>/evolucion/', views.evolucion_emergencia, name='evolucion_emergencia'),
    path('emergencias/<int:emergencia_id>/insumo/', views.insumo_emergencia, name='insumo_emergencia'),
    path('emergencias/<int:emergencia_id>/procedimiento/', views.procedimiento_emergencia, name='procedimiento_emergencia'),
    path('emergencias/<int:emergencia_id>/examen/', views.solicitar_examen_emergencia, name='solicitar_examen_emergencia'),

    # Compatibilidad URLs antiguas de emergencia
    path('registrar/', views.registrar_emergencia),
    path('lista/', views.lista_emergencias),
    path('emergencia/<int:emergencia_id>/triaje/', views.triaje_modal),
    path('emergencia/<int:emergencia_id>/triaje/ver/', views.ver_triaje),

    path('familiar/<int:familiar_id>/asignar-titular/', views.asignar_titular_familiar, name='asignar_titular_familiar'),
    path('familiares/asignar/', views.asignar_familiar_paciente, name='asignar_familiar_paciente'),

]
