# Generated by Django 5.0.1 on 2026-06-11 03:01

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_espe', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre_espe'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_exa', models.CharField(max_length=3, unique=True, verbose_name='Código del Examen')),
                ('nom_exa', models.CharField(max_length=30, verbose_name='Nombre del Examen')),
                ('tipo_exa', models.CharField(choices=[('LABORATORIO', 'LABORATORIO'), ('IMAGENEOLOGIA', 'IMAGENEOLOGIA'), ('OTROS', 'OTROS')], default='LABORATORIO', max_length=20, verbose_name='Tipo de Examen')),
                ('caracteristica_exa', models.CharField(blank=True, max_length=15, null=True, verbose_name='Características')),
                ('precio_exa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('creado_en_exa', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado_exa', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ins', models.CharField(max_length=20, unique=True, verbose_name='Código de Insumo')),
                ('nombre_ins', models.CharField(max_length=100, verbose_name='Nombre del Insumo')),
                ('presentacion_ins', models.CharField(max_length=100, verbose_name='Presentación (ej: caja, frasco, unidad)')),
                ('descripcion_ins', models.TextField(blank=True, null=True, verbose_name='Descripción / Observaciones')),
                ('cantidad_ins', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('precio_unitario_ins', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('fecha_caducidad_ins', models.DateField(verbose_name='Fecha de Caducidad')),
                ('proveedor_ins', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('creado_en_ins', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado_en_ins', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('stock_minimo', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Insumo Médico',
                'verbose_name_plural': 'Insumos Médicos',
                'ordering': ['fecha_caducidad_ins', 'nombre_ins'],
            },
        ),
        migrations.AlterModelOptions(
            name='doctorperfil',
            options={'ordering': ['especialidad__nombre_espe'], 'verbose_name': 'Doctor Perfil', 'verbose_name_plural': 'Perfiles Doctores'},
        ),
        migrations.AddField(
            model_name='doctorperfil',
            name='precio_consulta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Precio de Consulta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_cedula',
            field=models.CharField(choices=[('V', 'V'), ('E', 'E'), ('J', 'J'), ('G', 'G'), ('P', 'P')], default='V', max_length=5),
        ),
        migrations.AlterField(
            model_name='sliderimagen',
            name='titulo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'La cédula debe contener solo números')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='BCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcv_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BCV',
                'verbose_name_plural': 'BCV',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('ATENDIDA', 'Atendida'), ('NO_ASISTIO', 'No asistió')], default='PENDIENTE', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tasa_bcv_aplicada', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_doctor', to='consulta.doctorperfil')),
                ('paciente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'PACIENTE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('cedula', models.CharField(blank=True, max_length=8, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('nombre_paciente', models.CharField(blank=True, max_length=100)),
                ('apellido_paciente', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=12, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_consulta', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ALTA', 'Alta'), ('HOSPITALIZADO', 'Hospitalizado'), ('REFERIDO', 'Referido'), ('FALLECIDO', 'Fallecido')], default='ACTIVA', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'PACIENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.emergencia')),
            ],
        ),
        migrations.AlterField(
            model_name='doctorperfil',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctores', to='consulta.especialidad'),
        ),
        migrations.CreateModel(
            name='EvaluacionEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad_actual', models.TextField()),
                ('examen_fisico', models.TextField()),
                ('impresion_diagnostica', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.doctorperfil')),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='consulta.emergencia')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.doctorperfil')),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='consulta.emergencia')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_bcv_fijada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulta.citamedica')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliarPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=12)),
                ('fecha_nacimiento', models.DateField(default=datetime.date(2000, 1, 1))),
                ('parentesco', models.CharField(blank=True, choices=[('HIJO', 'Hijo'), ('MADRE', 'Madre'), ('PADRE', 'Padre'), ('ESPOSA', 'Esposa'), ('HERMANO', 'Hermano'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('paciente_titular', models.ForeignKey(blank=True, limit_choices_to={'rol': 'PACIENTE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emergencia',
            name='familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias', to='consulta.familiarpaciente'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_familiar', to='consulta.familiarpaciente'),
        ),
        migrations.CreateModel(
            name='HistoriaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('enfermedades_cronicas', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('familiar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historia_medica', to='consulta.familiarpaciente')),
                ('paciente', models.OneToOneField(blank=True, limit_choices_to={'rol': 'PACIENTE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historia_medica', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='examenes_medicos/%Y/%m/%d/')),
                ('fecha_examen', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('historia_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='consulta.historiamedica')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='consulta.doctorperfil')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='consulta.emergencia')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.insumomedico')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_insumos', to='consulta.citamedica')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta.insumomedico')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.emergencia')),
            ],
        ),
        migrations.CreateModel(
            name='RealizarExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta.citamedica')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_doctor', to='consulta.doctorperfil')),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta.examen')),
                ('familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examen_familiar', to='consulta.familiarpaciente')),
                ('paciente', models.ForeignKey(limit_choices_to={'rol': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_actual', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='consulta.citamedica')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='consulta.insumomedico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('realizar_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='consulta.realizarexamen')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.examen')),
                ('realizar_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_realizados', to='consulta.realizarexamen')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.insumomedico')),
                ('realizar_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='consulta.realizarexamen')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudExamenEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_examen', to='consulta.emergencia')),
                ('realizar_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.realizarexamen')),
            ],
        ),
        migrations.CreateModel(
            name='TriajeEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=20)),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.PositiveIntegerField(blank=True, null=True)),
                ('saturacion_oxigeno', models.PositiveIntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prioridad', models.CharField(choices=[('ROJO', 'Rojo'), ('NARANJA', 'Naranja'), ('AMARILLO', 'Amarillo'), ('VERDE', 'Verde'), ('AZUL', 'Azul')], max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triajes', to='consulta.emergencia')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bcv',
            constraint=models.UniqueConstraint(fields=('fecha',), name='bcv_unico_por_dia'),
        ),
        migrations.AddConstraint(
            model_name='citamedica',
            constraint=models.UniqueConstraint(fields=('doctor', 'fecha', 'hora'), name='unique_cita_doctor_fecha_hora'),
        ),
    ]
